version: '3.0'

services:
  grafana:
    container_name: 'esnet-matrix-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-12.0.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/esnet-matrix-panel
      - ./provisioning:/etc/grafana/provisioning
